// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQz4QBTBdYxMSn79KFnZoVWntrjIaQJh4',
    appId: '1:249450735887:web:70d8c4d39aeb8f6238767a',
    messagingSenderId: '249450735887',
    projectId: 'aung-1756e',
    authDomain: 'aung-1756e.firebaseapp.com',
    storageBucket: 'aung-1756e.firebasestorage.app',
    measurementId: 'G-08V80YY2JG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7nEx4x06gnWCXPst8fCWO9ZynGa9L4hY',
    appId: '1:249450735887:android:d64e7a0d30d3e18c38767a',
    messagingSenderId: '249450735887',
    projectId: 'aung-1756e',
    storageBucket: 'aung-1756e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSmxiBtu_H7_Ci5gooY94JTTjWDYa4ags',
    appId: '1:249450735887:ios:a55fa4a7f71dc11d38767a',
    messagingSenderId: '249450735887',
    projectId: 'aung-1756e',
    storageBucket: 'aung-1756e.firebasestorage.app',
    iosBundleId: 'com.example.fly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSmxiBtu_H7_Ci5gooY94JTTjWDYa4ags',
    appId: '1:249450735887:ios:a55fa4a7f71dc11d38767a',
    messagingSenderId: '249450735887',
    projectId: 'aung-1756e',
    storageBucket: 'aung-1756e.firebasestorage.app',
    iosBundleId: 'com.example.fly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQz4QBTBdYxMSn79KFnZoVWntrjIaQJh4',
    appId: '1:249450735887:web:ecef3292af98a6b238767a',
    messagingSenderId: '249450735887',
    projectId: 'aung-1756e',
    authDomain: 'aung-1756e.firebaseapp.com',
    storageBucket: 'aung-1756e.firebasestorage.app',
    measurementId: 'G-FSJJVF23JG',
  );
}
